modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/nonamecrackers2/simple-clouds/issues" #optional

[[mods]]
	modId="${mod_id}"
	version="${mod_version}"
	displayName="${mod_name}"
	#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
	displayURL="https://modrinth.com/project/simple-clouds" #optional
	logoFile="simpleclouds.png" #optional
	#credits="" #optional
	authors="${mod_authors}" #optional
	description='''${mod_description}'''

[[mixins]]
    config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]] #optional
    modId="neoforge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.${mod_id}]]
    modId="crackerslib"
    mandatory=true
    versionRange="${crackerslib_version_range}"
    ordering="NONE"
    side="BOTH"

[features.${mod_id}]
openGLVersion="[4.3,)"