name: Feature Request
description: Suggest an idea for the mod
title: "[Suggestion]: "
labels: ["suggestion"]
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # !!! [Please read the guidelines before submitting](https://github.com/nonamecrackers2/simple-clouds/blob/1.20.1/docs/CONTRIBUTING.md)

        # Only one feature suggestion per issue
  - type: checkboxes
    id: read-guidelines
    attributes:
      label: Guidelines
      options:
        - label: By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description of feature request
      placeholder: "Describe what you'd like to see in the mod. Don't spare the details!"
    validations:
      required: true
